# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checking for missing change logs...
        run: node common/scripts/install-run-rush.js change -v

      - name: Installing...
        run: node common/scripts/install-run-rush.js install

      - name: Building...
        run: node common/scripts/install-run-rush.js rebuild --verbose

      - name: Testing...
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 146fae79fffee30a166379a8e5e97beb4582e67af958ae0315dcb538af56cbac
        with:
          coverageCommand: common/scripts/coverage.sh
          coverageLocations: |
            ${{github.workspace}}/packages/status/coverage/lcov.info:lcov
            ${{github.workspace}}/packages/platform/coverage/lcov.info:lcov
            ${{github.workspace}}/packages/query/coverage/lcov.info:lcov
