# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checking for mis-matching dependencies...
        run: node common/scripts/install-run-rush.js check

      - name: Checking for missing change logs...
        run: node common/scripts/install-run-rush.js change -v

      - name: Installing...
        run: node common/scripts/install-run-rush.js install

      - name: Building...
        run: node common/scripts/install-run-rush.js rebuild --verbose

      - uses: getong/elasticsearch-action@v1.2
        with:
          elasticsearch version: '7.12.0'
          host port: 9200
          container port: 9200
          host node port: 9300
          node port: 9300
          discovery type: 'single-node'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4

      - name: Testing...
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 146fae79fffee30a166379a8e5e97beb4582e67af958ae0315dcb538af56cbac
        with:
          coverageCommand: common/scripts/each-x.sh test
          coverageLocations: |
            ${{github.workspace}}/packages/*/coverage/lcov.info:lcov
            ${{github.workspace}}/plugins/*/coverage/lcov.info:lcov
            ${{github.workspace}}/server/*/coverage/lcov.info:lcov
      
      - name: Build Demo
        run: |
          cd ./dev/prod
          node ../../common/scripts/install-run-rushx.js build-demo
      
      - name: Deploy Demo
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          

  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Installing...
        run: node common/scripts/install-run-rush.js install
      
      - name: Building...
        run: node common/scripts/install-run-rush.js build

      - name: Check files formatting
        run: |
          common/scripts/each-x.sh format
          echo '================================================================'
          echo 'Checking for diff files'
          echo '================================================================'
          git diff '*.ts' '*.svelte' | cat
          [ -z "$(git diff --name-only '*.ts' '*.svelte' | cat)" ]
          echo '================================================================'

